# Generated by Django 2.0.5 on 2018-05-09 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('dirid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='主目录ID')),
                ('parentid', models.CharField(max_length=8, verbose_name='父ID')),
                ('name', models.CharField(max_length=255, verbose_name='目录名称')),
                ('tree', models.CharField(max_length=255, verbose_name='树串ID')),
                ('roleset', models.CharField(max_length=255, verbose_name='角色集')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('info', models.TextField(verbose_name='说明信息')),
                ('log', models.TextField(verbose_name='日志信息')),
            ],
            options={
                'verbose_name': '目录信息表',
                'verbose_name_plural': '目录信息表',
            },
        ),
    ]
